# Generated by Django 5.2.4 on 2025-07-29 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False, verbose_name='브랜드 식별자')),
                ('name', models.CharField(max_length=225, verbose_name='브랜드 명')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False, verbose_name='제품 식별자')),
                ('name', models.CharField(max_length=255, verbose_name='제품 이름')),
                ('category', models.CharField(max_length=255, verbose_name='제품 카테고리')),
                ('url', models.TextField(blank=True, null=True, verbose_name='제품 링크')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='제품 가격')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='사이트별 제품코드')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='moodico.brand', verbose_name='브랜드')),
            ],
        ),
        migrations.CreateModel(
            name='ProductShade',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False, verbose_name='제품 셰이드 식별자')),
                ('tone_tag_id', models.CharField(blank=True, max_length=225, null=True, verbose_name='톤 태그 ID')),
                ('hex', models.CharField(blank=True, max_length=225, null=True, verbose_name='색상 HEX')),
                ('lab_l', models.FloatField(blank=True, null=True, verbose_name='명도(L)')),
                ('lab_a', models.FloatField(blank=True, null=True, verbose_name='채도(G/R)')),
                ('lab_b', models.FloatField(blank=True, null=True, verbose_name='채도(B/Y)')),
                ('shade_name', models.CharField(max_length=255, verbose_name='셰이드 이름')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shades', to='moodico.product', verbose_name='제품')),
            ],
        ),
    ]
