# Generated by Django 5.2.4 on 2025-08-01 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='분석 결과 식별자')),
                ('primary_hex', models.CharField(max_length=225, verbose_name='대표 HEX')),
                ('palette_json', models.JSONField(verbose_name='팔레트 JSON')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='브랜드 식별자')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='브랜드 명')),
            ],
        ),
        migrations.CreateModel(
            name='ToneTag',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False, verbose_name='톤 태그 식별자')),
                ('code', models.CharField(max_length=225, verbose_name='색상코드')),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20, verbose_name='계절')),
                ('subtype', models.CharField(choices=[('bright', 'Bright'), ('light', 'Light'), ('deep', 'Deep'), ('soft', 'Soft')], max_length=20, verbose_name='색상 명도 유형')),
            ],
        ),
        migrations.CreateModel(
            name='PaletteColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='팔레트 컬러 식별자')),
                ('hex', models.CharField(max_length=7, verbose_name='HEX')),
                ('lab_l', models.FloatField(verbose_name='명도(L)')),
                ('lab_a', models.FloatField(verbose_name='채도(G/R)')),
                ('lab_b', models.FloatField(verbose_name='채도(B/Y)')),
                ('sort_order', models.IntegerField(verbose_name='정렬 순서')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palette_colors', to='moodico.analysisresult', verbose_name='분석 결과')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='제품 식별자')),
                ('name', models.CharField(max_length=255, verbose_name='제품 이름')),
                ('category', models.CharField(max_length=255, verbose_name='제품 카테고리')),
                ('url', models.URLField(blank=True, null=True, verbose_name='제품 링크')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='제품 가격')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='사이트별 제품코드')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodico.brand', verbose_name='브랜드')),
            ],
        ),
        migrations.CreateModel(
            name='ProductShade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='제품 셰이드 식별자')),
                ('hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='색상 HEX')),
                ('lab_l', models.FloatField(blank=True, null=True, verbose_name='명도(L)')),
                ('lab_a', models.FloatField(blank=True, null=True, verbose_name='채도(G/R)')),
                ('lab_b', models.FloatField(blank=True, null=True, verbose_name='채도(B/Y)')),
                ('shade_name', models.CharField(max_length=255, verbose_name='셰이드 이름')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shades', to='moodico.product', verbose_name='제품')),
                ('tone_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moodico.tonetag', verbose_name='톤 태그')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='추천 식별자')),
                ('score', models.IntegerField(verbose_name='점수')),
                ('rank', models.IntegerField(verbose_name='순위')),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodico.analysisresult', verbose_name='분석 결과')),
                ('product_shade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodico.productshade', verbose_name='추천된 셰이드')),
            ],
            options={
                'ordering': ['rank', '-score'],
            },
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='tone_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodico.tonetag', verbose_name='톤 태그'),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='업로드 식별자')),
                ('status', models.CharField(default='pending', max_length=225, verbose_name='상태')),
                ('image_path', models.ImageField(upload_to='uploads/', verbose_name='이미지 경로')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodico.upload', verbose_name='업로드'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='유저 프로필 식별자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='프로필 생성 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='프로필 업데이트 날짜')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='노트')),
                ('color_type', models.CharField(blank=True, max_length=225, null=True, verbose_name='컬러 타입')),
                ('default_tone_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moodico.tonetag', verbose_name='기본 톤 태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
    ]
