# Generated by Django 5.2.4 on 2025-08-05 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='좋아요 식별자')),
                ('product_id', models.CharField(max_length=255, verbose_name='제품 ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='제품명')),
                ('product_brand', models.CharField(max_length=255, verbose_name='브랜드')),
                ('product_price', models.CharField(max_length=100, verbose_name='가격')),
                ('product_image', models.URLField(blank=True, null=True, verbose_name='제품 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='좋아요 날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product_id')},
            },
        ),
    ]
