# Generated by Django 5.2.4 on 2025-08-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodico', '0002_usermood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMood',
        ),
    ]
