# Generated by Django 5.2.4 on 2025-08-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodico', '0002_productlike'),
        ('moodico', '0003_delete_usermood'),
    ]

    operations = [
    ]
