# Generated by Django 5.2.4 on 2025-08-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodico', '0007_userprofile_mood_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlike',
            name='product_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
