# Generated by Django 5.2.4 on 2025-08-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodico', '0008_productlike_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlike',
            name='product_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='color_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_tone_tag',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
