# Generated by Django 5.2.4 on 2025-08-06 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="추천 식별자",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="점수")),
                ("rank", models.IntegerField(verbose_name="순위")),
            ],
            options={
                "ordering": ["rank", "-score"],
            },
        ),
        migrations.CreateModel(
            name="ToneTag",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=225,
                        primary_key=True,
                        serialize=False,
                        verbose_name="톤 태그 식별자",
                    ),
                ),
                ("code", models.CharField(max_length=225, verbose_name="색상코드")),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                        ],
                        max_length=20,
                        verbose_name="계절",
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("bright", "Bright"),
                            ("light", "Light"),
                            ("deep", "Deep"),
                            ("soft", "Soft"),
                        ],
                        max_length=20,
                        verbose_name="색상 명도 유형",
                    ),
                ),
            ],
        ),
    ]
