# Generated by Django 5.2.4 on 2025-08-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_initial"),
        ("recommendation", "0001_initial"),
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="analysis_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.analysisresult",
                verbose_name="분석 결과",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="product_shade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productshade",
                verbose_name="추천된 셰이드",
            ),
        ),
    ]
