# Generated by Django 5.2.4 on 2025-08-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedproduct',
            name='price',
            field=models.CharField(max_length=100, verbose_name='가격'),
        ),
    ]
