# Generated by Django 5.2.4 on 2025-08-06 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="브랜드 식별자",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="브랜드 명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="제품 식별자",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="제품 이름")),
                ("category", models.CharField(max_length=255, verbose_name="제품 카테고리")),
                ("url", models.URLField(blank=True, null=True, verbose_name="제품 링크")),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="제품 가격"
                    ),
                ),
                (
                    "external_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="사이트별 제품코드"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.brand",
                        verbose_name="브랜드",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="좋아요 식별자",
                    ),
                ),
                ("product_id", models.CharField(max_length=255, verbose_name="제품 ID")),
                ("product_name", models.CharField(max_length=255, verbose_name="제품명")),
                ("product_brand", models.CharField(max_length=255, verbose_name="브랜드")),
                ("product_price", models.CharField(max_length=100, verbose_name="가격")),
                (
                    "product_image",
                    models.URLField(blank=True, null=True, verbose_name="제품 이미지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="좋아요 날짜"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductShade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="제품 셰이드 식별자",
                    ),
                ),
                (
                    "hex",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="색상 HEX"
                    ),
                ),
                (
                    "lab_l",
                    models.FloatField(blank=True, null=True, verbose_name="명도(L)"),
                ),
                (
                    "lab_a",
                    models.FloatField(blank=True, null=True, verbose_name="채도(G/R)"),
                ),
                (
                    "lab_b",
                    models.FloatField(blank=True, null=True, verbose_name="채도(B/Y)"),
                ),
                ("shade_name", models.CharField(max_length=255, verbose_name="셰이드 이름")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shades",
                        to="products.product",
                        verbose_name="제품",
                    ),
                ),
            ],
        ),
    ]
