# Generated by Django 5.2.4 on 2025-08-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productshade",
            name="tone_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recommendation.tonetag",
                verbose_name="톤 태그",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productlike",
            unique_together={("user", "product_id")},
        ),
    ]
