# Generated by Django 5.2.4 on 2025-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productlike_session_nickname_alter_productlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlike',
            name='product_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
