# Generated by Django 5.2.4 on 2025-08-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productlike_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlike',
            name='product_url',
        ),
    ]
