# Generated by Django 5.2.4 on 2025-08-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productlike_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlike',
            name='product_url',
            field=models.URLField(blank=True, null=True, verbose_name='제품 URL'),
        ),
    ]
