# Generated by Django 5.2.4 on 2025-08-10 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productlike_product_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='별점 식별자')),
                ('session_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='세션 닉네임')),
                ('product_id', models.CharField(max_length=255, verbose_name='제품 ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='제품명')),
                ('product_brand', models.CharField(max_length=255, verbose_name='브랜드')),
                ('rating', models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='별점')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='리뷰 코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='별점 작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='별점 수정일')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product_id')},
            },
        ),
    ]
