# Generated by Django 5.2.4 on 2025-08-16 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productratingimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='투표 식별자')),
                ('session_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='세션 닉네임')),
                ('product_id', models.CharField(max_length=255, verbose_name='제품 ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='제품명')),
                ('product_brand', models.CharField(max_length=255, verbose_name='브랜드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='투표 날짜')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product_id')},
            },
        ),
    ]
