<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-17 03:44
=======
# Generated by Django 5.2.4 on 2025-08-17 02:56
>>>>>>> a3f16f12cb8cafbfab5ff80a44f7486af32ca3b5

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_productvote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductVote",
        ),
    ]
