# Generated by Django 5.2.4 on 2025-08-17 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_productvote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductVote",
        ),
    ]
