# Generated by Django 4.2.23 on 2025-08-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_uploadedimage'),
        ('products', '0011_delete_productvote'),
    ]

    operations = [
    ]
