# Generated by Django 4.2.23 on 2025-08-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_merge_0002_uploadedimage_0011_delete_productvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
