# Generated by Django 5.2.4 on 2025-08-06 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recommendation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="분석 결과 식별자",
                    ),
                ),
                (
                    "primary_hex",
                    models.CharField(max_length=225, verbose_name="대표 HEX"),
                ),
                ("palette_json", models.JSONField(verbose_name="팔레트 JSON")),
                (
                    "tone_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendation.tonetag",
                        verbose_name="톤 태그",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaletteColor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="팔레트 컬러 식별자",
                    ),
                ),
                ("hex", models.CharField(max_length=7, verbose_name="HEX")),
                ("lab_l", models.FloatField(verbose_name="명도(L)")),
                ("lab_a", models.FloatField(verbose_name="채도(G/R)")),
                ("lab_b", models.FloatField(verbose_name="채도(B/Y)")),
                ("sort_order", models.IntegerField(verbose_name="정렬 순서")),
                (
                    "analysis_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palette_colors",
                        to="upload.analysisresult",
                        verbose_name="분석 결과",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="업로드 식별자",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=225, verbose_name="상태"
                    ),
                ),
                (
                    "image_path",
                    models.ImageField(upload_to="uploads/", verbose_name="이미지 경로"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.upload",
                verbose_name="업로드",
            ),
        ),
    ]
