# Generated by Django 5.2.4 on 2025-08-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="color_type",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_tone_tag",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mood_result",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="무드 테스트 결과"
            ),
        ),
    ]
