# Generated by Django 5.2.4 on 2025-08-06 20:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0002_initial"),
        ("users", "0002_remove_userprofile_color_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="color_type",
            field=models.CharField(
                blank=True, max_length=225, null=True, verbose_name="컬러 타입"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 8, 7, 5, 19, 54, 47501),
                verbose_name="프로필 생성 날짜",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_tone_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recommendation.tonetag",
                verbose_name="기본 톤 태그",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="노트"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="프로필 업데이트 날짜"
            ),
        ),
    ]
