name: Django CI/CD

on:
  workflow_dispatch:
  push:
    branches: ["main", "main-test"]
  pull_request:
    branches: ["main"]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    # run on push to main or main-test, or when manually triggered
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/main-test')) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}          # raw multi-line private key (BEGIN/END + newlines)
          # passphrase: ${{ secrets.KEY_PASSPHRASE }}   # only if your key has one
          script: |
            set -e
            cd /home/ubuntu/Moodico
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart nginx