name: Django CI/CD

on:
  workflow_dispatch:
  push:
    branches: ["main", "main-test"]
  pull_request:
    branches: ["main"]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/main-test')) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Write SSH key (decode base64 secret) into workspace
        run: |
          set -e
          printf '%s' "${{ secrets.KEY }}" | base64 --decode --ignore-garbage > "${GITHUB_WORKSPACE}/gha_key"
          chmod 600 "${GITHUB_WORKSPACE}/gha_key"
          head -n1 "${GITHUB_WORKSPACE}/gha_key"   # should print BEGIN line

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key_path: ${{ github.workspace }}/gha_key   # 🔑 use workspace path
          script: |
            set -e
            cd /home/ubuntu/Moodico
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart nginx