name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test
          
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      # 1) Decode base64 secret into a real private key file
      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" | base64 -d > ~/.ssh/gha_key
          chmod 600 ~/.ssh/gha_key

      # 2) Deploy over SSH (use key_path, not key)
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key_path: ~/.ssh/gha_key
          script: |
            set -e
            cd /home/ubuntu/Moodico
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart nginx



